sudo: required

services:
  - docker

before_install:
  - docker build -t cry0genic/docker-react -f Dockerfile.dev .

script:
  - docker run cry0genic/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk  
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-761185896481"
  bucket_path: "docker"
  on:
    branch: master

  access_key_id: $"AWS_ACCESS_KEY"
  secret_access_key: 
    secure: $"AWS_SECRET_KEY"